### ISSUE TITLE
CBL 2.5.0 is not able to migrate db for 1.4

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android-ce#1]
TestServer App crashes while loading CBL 1.4 db.

### Python client logs - 
[python_client.log](https://github.com/couchbase/couchbase-lite-android/files/3252427/python_client.log)

### CBL logs - 

[logs_1559652425.zip](https://github.com/couchbase/couchbase-lite-android/files/3252428/logs_1559652425.zip)

[adb_logs.log](https://github.com/couchbase/couchbase-lite-android/files/3255416/adb_logs.log)

Test command -

1. git clone https://github.com/couchbaselabs/mobile-testkit.git
2. git checkout feature/cbl-upgrade-testing
3. pytest -rsx -s  --skip-provisioning --timeout 3600 --base-liteserv-version=1.4 --upgraded-liteserv-version=2.5.0-224 --liteserv-host=192.168.0.144 --liteserv-port=8080 --sync-gateway-version=2.5.0-269 --mode=cc --server-version=6.0.0-1693 --liteserv-platform=android --enable-file-logging testsuites/CBLTester/upgrade_tests/test_cbl_upgrade.py

CBL db is available at - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl-upgrade-testing/CBLClient/Apps/CBLTestServer-Android/app/src/main/assets/travel-sample-1.4.cblite2.zip

**Comment by bmeike** [comment]
We'll need the logcat to get anywhere with this.  Please attach it.

**Comment by hrajput89** [comment]
I've logged Jira ticket - https://issues.couchbase.com/browse/CBL-204. 

Closing ticket here.
