### ISSUE TITLE
Just observe if changes happen to a Query. 

### ISSUE THREAD

**Issue by vander2675** [couchbase/couchbase-lite-android-ce#13]
Hello, 
Currently I’m implementing the Data Source Objects from the Paging Library in the Android Jetpack Components in combination with Couchbase Lite for Android. 

For this to work I need a notification from Couchbase that the Result of an Query changed, without loading the Properties into memory. 

Is this possible with the current accessible methods?

Thank you very much in Advance

**Comment by bmeike** [comment]
Hey @vander2675 , I'm guessing you've already found another solution for this.  I'm going to close the ticket.  Feel free to re-open it if there is more that we can do.
