### ISSUE TITLE
Initial delay in livequery of 2.5.2

### ISSUE THREAD

**Issue by MatFl** [couchbase/couchbase-lite-android-ce#17]
In 2.5.0 when starting a livequery the update was executed with 0 delay, only later updates would be delayed by 200ms.

In 2.5.2 also the initial update is delayed. (Changed with commit #29abb297daa6d3dacb5e82fc0a81766ee2e275dd)
This seems counterproductive, as when using livequery to fill a listview, the initial data comes very late.

**Comment by bmeike** [comment]
This bug is being tracked [here](https://issues.couchbase.com/browse/CBL-172)

**Comment by bmeike** [comment]
Fixed in couchbase-lite-java: 95e99be88fea1a4

**Comment by bmeike** [comment]
Fixed in master.

**Comment by RocketRider** [comment]
I really hoped the fix would be included in 2.6, but it seems as it is not included.

**Comment by bmeike** [comment]
My apologies.  I acknowledge that this is a bug and a regression.  I did not get it fixed in time to get it over the release bar for 2.6.  Sorry.
