### ISSUE TITLE
Enhance query builder : create complex query

### ISSUE THREAD

**Issue by seb-bisson** [couchbase/couchbase-lite-android-ce#18]
We want to build a query given different parameters (with/without where expression, with/without orderby expression, with/without limit expression, ...).

Actually, it's not possible to build a complex query with builder.
The only solution we found is to create a query for each situation (more than 10) wich is not optimal and very complex to maintain.

Example: today we handle where expression this way:
```java
       Query query = null;
        Expression expression = getFilterExpression(filter);
        if (expression != null) {
            query = from.where(expression);
        } else {
            query = from;
        }
```
Now we want to add or not other conditions.

Do you have any clue to resolve our problems?

**Comment by seb-bisson** [comment]
It should be usefull to be close to builder pattern:

https://en.wikipedia.org/wiki/Builder_pattern

**Comment by bmeike** [comment]
It is true that you cannot build a complex expression using the `QueryBuilder`.  You can, however, build a complex expression using the Expression builder, and then add it to the query.  Is that not sufficient?

**Comment by seb-bisson** [comment]
The expression builder permit to add multiple fields/expression. 
And I'me using it this way.

As I'm writing a cordova plugin, i would like to allow adding sortbyexpression and/or a group by expression and/or a limitExpression as a plugin user could use it.

Does it make sense for you?

**Comment by bmeike** [comment]
I can file this as a feature request, but I don't think it is going to get a lot of attention.  You can already do what you are asking, by using a combination of a `QueryBuilder` and an `ExpressionBuilder`.  This is syntactic sugar.

**Comment by bmeike** [comment]
Hey @seb-bisson : Do you have more thoughts on this?  I'll close this, if you are good.
