### ISSUE TITLE
Memory Leak: Database reference held by a ReplicatorListenerThread after close

### ISSUE THREAD

**Issue by fijemax** [couchbase/couchbase-lite-android-ce#2]
Hello,

Using: CB 2.1.0
I inspect my app memory after stop my two replicators and closing and releasing my Database.

I observed that the both replicators are keep by  a ReplicatorListenerThread and by the same way the Database reference's is keep too.

Note:
All references at any couchbase Documents or Database are release by my app.
I force Garbage Collecte to release memory.
The database was closed after both Replication has stopped properly.

This is memory leak or normal behavior ?

**Comment by bmeike** [comment]
This issue is also tracked in https://issues.couchbase.com/browse/CBL-15

**Comment by bmeike** [comment]
This issue has been resolved.  The fix is in couchbase-lite-java:f020addb3aeeec67b98f32be and was released with CBL 2.6.x
