### ISSUE TITLE
Shouldn't Dictionary be Parcelable?

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [couchbase/couchbase-lite-android-ce#3]
In one case, I happen to put a Dictionary into a HashMap and pass it to a fragment. This caused a RunTimeException stating, the Parcel was unable to mash the value which is a Dictionary.

Shouldn't Dictionary be Parcelable? or is there better way to share a dictionary?

**Comment by bmeike** [comment]
I've created https://issues.couchbase.com/browse/CBL-18 to track this issue.  Please  follow it there.
