### ISSUE TITLE
Error using 'IN' clause in Android

### ISSUE THREAD

**Issue by geraldapeoples** [couchbase/couchbase-lite-android-ce#39]
Error when using 'IN' clause in Android.

The following statement gives an error when trying to execute it -

`SELECT META().id,
               asset_type,
               asset_form_config_id,
               lifecycle
FROM _
WHERE type = "asset"
AND META().id IN ("c1ed06cc296841a7a75f04df8f99da9f")
ORDER BY asset_type DESC`

If we swap the WHERE/AND the following statement runs and give the correct result -

`SELECT META().id,
                 asset_type,
                 asset_form_config_id,
                 lifecycle
FROM _
WHERE META(t).id IN ("c1ed06cc296841a7a75f04df8f99da9f")
AND type = "asset"
ORDER BY asset_type DESC`

**Comment by bmeike** [comment]
Totally missed this.
There is not enough information to address the problem: version of the platform, actual error, etc. etc.
Question is stale, now.  Closing
