### ISSUE TITLE
Please make `DictionaryInterface` interface public

### ISSUE THREAD

**Issue by AlBlanc** [couchbase/couchbase-lite-android-ce#8]
Hello CB team,

I am writing an ORM for couchbase lite 2.0 and i am getting stuck. I need `DictionaryInterface` to be public to make a common flow usable for Document and Dictionnary (for nested object)

Thank you!

**Comment by bmeike** [comment]
Opened https://issues.couchbase.com/browse/CBL-32 to track this.  Please follow it there.
